### ISSUE TITLE
Http\ClientFactory mergeOptions

### ISSUE THREAD

**Issue by ribizli** [ivan-novakov/php-openid-connect-client#10]
Missing parameter for $preserveNumericKeys which should be true. Otherwise it is not possible to override the curloptions (they are numeric constants).

```php
    public function mergeOptions($options)
    {
        return ArrayUtils::merge($this->defaultOptions, ArrayUtils::iteratorToArray($options), true);
    }
```

**Comment by bradjones1** [comment]
@ribizli I believe this should have been fixed by https://github.com/ivan-novakov/php-openid-connect-client/pull/11 - let me know if this is a different issue.
