### ISSUE TITLE
Validate other logins

### ISSUE THREAD

**Issue by fulldecent** [ivan-novakov/php-openid-connect-client#12]
This website lists OpenID Connect providers:

https://stackoverflow.com/questions/10488973/openid-connect-providers

Major ones include:

AOL
eBay
Google
Heroku
Orange

Please validate and confirm if these work with your project.

**Comment by bradjones1** [comment]
@fulldecent Pull requests and tests are welcome!

**Comment by themornstars** [comment]
<h1># Nokia 230 Original </h1>__
**_Nokia 230 Original_**

> Nokia 230 Original
`Nokia 230 Original`
Nokia 230 Original
