### ISSUE TITLE
Issues with windows Azure

### ISSUE THREAD

**Issue by theD1360** [ivan-novakov/php-openid-connect-client#3]
```
Exception during user authentication: [InoOicClient\Flow\Exception\TokenRequestException] Exception during token request: [InoOicClient\Oic\Exception\ErrorResponseException] Error response from server 'invalid_request' (ACS50001: The required field 'resource' is missing. Trace ID: ff9abb57-2000-46c8-9fc7-71ebc2275dd2 Correlation ID: bfd8e42e-82f0-4ee6-aec7-70e0064fb21a Timestamp: 2014-05-29 18:17:55Z)
```

This is the error I receive in the callback. Any idea as to what would be causing this?

**Comment by LarsKemmann** [comment]
Wow, I wish I had found this two days ago! I've been troubleshooting this (see http://stackoverflow.com/questions/28415234/whats-wrong-with-this-authorization-exchange) for several days, making slow progress - and largely reproducing some of the work you've done. :) I'll see if I can get further with the pull request you started.

**Comment by theD1360** [comment]
@LarsKemmann I'm glad someone got some use out of it. It was a real pain working with microsoft azure.
