### ISSUE TITLE
composer not working

### ISSUE THREAD

**Issue by josephhr** [ivan-novakov/php-openid-connect-client#9]
Dear Ivan,

sorry since I am very new in this stuff but I downloaded the code, and typed composer "php composer.phar install" with this error:
"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ivan-novakov/php-openid-connect-client 1.0.0 could not be found"

Thanks and regards

**Comment by ivan-novakov** [comment]
Joseph,

there is no version 1.0.0 yet :). What did you actually do? If you clone the repository and from inside the root directory you run "composer install", it will install the dependencies - some ZF parts. You probably tried to add this library to an existing project. So try to put:

"ivan-novakov/php-openid-connect-client": "dev-master"

or with specific version:

"ivan-novakov/php-openid-connect-client": "0.2.0"

in your composer.json file.
